server:
  name: go-pubsub-sample
  port: 8080

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

firestore:
  project_id:
  credentials:

handler:
  key: key
  goroutines: true
  retry:
    1: 5
    2: 7
    3: 9

sub:
  subscription_id: users-sub
  subscription:
    max_outstanding_messages: 10000000
    num_goroutines: 5
  client:
    credentials:

pub:
  topic_id: users
  topic:
    delay_threshold: 100
    count_threshold: 1
  client:
    credentials: